spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://CrispMallUser
          predicates:
            - Path=/user/**

        - id: order_route
          uri: lb://CrispMallOrder
          predicates:
            - Path=/order/**

        - id: product_route
          uri: lb://CrispMallProduct
          predicates:
            - Path=/product/**

        - id: oss_route
          uri: lb://CrispMallOss
          predicates:
            - Path=/oss/**