spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, hh

        - id: user_route
          uri: lb://CrispMallUser
          predicates:
            - Path=/user/**